/**
 * @file KnexDAO
 * @author Jim Bulkowski <jim.b@paperelectron.com>
 * @project knex-core
 * @license MIT {@link http://opensource.org/licenses/MIT}
 */

import {CreatePlugin} from "@pomegranate/plugin-tools";
import {get, isFunction,map, reduce, capitalize, toLower, fromPairs} from 'lodash/fp'
const tsGenerator = `// Generated by the Pomegranate cli on {{creationDate}}

// name: {{name}}


export const DAO = (PluginLogger, Knex) => {
  
  return {
    create: (name: string) => {
      return Knex('mytable')
      .insert({name: name})
      .returning('*')
    }
  }
}
`

export const KnexDAO = CreatePlugin('anything')
  .directories([{prop: 'main', path: '.'}])
  .configuration({
    name: 'KnexDAO',
    injectableParam: 'SQL',
    depends: ['@pomofficial/KnexClient']
  })
  .hooks({
    load: async (Injector,PluginVariables, PluginFiles, PluginLogger) => {
      let files = await PluginFiles('main').fileList({ext: '.js'})
      return fromPairs(map((file) => {
        let required = require(file.path)
        let fileName = file.getBaseName()

        PluginLogger.log(`Found DAO: ${fileName}.`, 2)

        let M = get('DAO', required)
        if (!M) {
          throw new Error(`Model file ${fileName} does not contain an export on the DAO property.`)
        }
        if (!isFunction(M)) {
          throw new Error(`Model file ${fileName} does not export an injectable function on the DAO property.`)
        }

        return [fileName, Injector.inject(M)]
      }, files))

    }
  })
  .commands(function (PomConfig, PluginFiles, Handlebars) {
    return (yargs) => {
      return yargs
        .usage('usage: $0')
        .command({
          command: 'generate <name>',
          aliases: 'g',
          describe: `Generates DAO file <name>`,
          builder: (yargs) => {
            return yargs
              .positional('name', {
                describe: 'The the filename to be created.',
                default: 'index',
                type: 'string'
              })
              .option('l', {
                alias: 'language',
                describe: 'Generate TypeScript or Javascript',
                default: 'ts',
                choices: ['ts'],
                type: 'string'
              })
              .option('force', {
                alias: 'f',
                default: false,
                describe: 'overwrites the specified file if it exists.',
                type: 'boolean'
              })
          },
          handler: async (argv) => {
            let Pf = PluginFiles('main')
            let file = `${argv.name}.${argv.language}`
            let exists = await Pf.projectFileExists(file)
            let compile = Handlebars.compile(tsGenerator)
            let upperName = argv.name
            let lowerName = toLower(argv.name)
            let compiled = compile({
              creationDate: new Date().toDateString(),
              name: argv.name,
              upperName,
              lowerName
            })

            if (exists && !argv.force) {
              throw new Error(`${file} \n exists \n Rerun with --force to overwrite.`)
            }
            await Pf.outputProjectFile(file, compiled)
            console.log(`Created @pomofficial/KnexDAO file ${file}`)
          }
        })
        .help()
    }
  })